### ISSUE TITLE
Hide your API key !

### ISSUE THREAD

**Issue by Shigumitsu** [hectocore/slackbot-miller#1]
Hey @hectocore !

**For security reasons**, I suggest you to remove your API key in `bot/slackbot_settings.py` and regenerate the key on Slack.

Best regards,

**Comment by hectocore** [comment]
Hi @Shigumitsu !

This API key is actually not linked to anything (I don’t post active ones on Github, it’s common sense).

Anyway, thank you for your concerns about the security of my applications!
